# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HTML Email
email: lee@leemunroe.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://htmlemail.io" # the base hostname & protocol for your site
enforce_ssl: htmlemail.io
twitter_username: htmlemailio
github_username:  leemunroe
permalink: /blog/:title

# Build settings
markdown: kramdown
theme: minima

# Exclude
exclude: ['node_modules', 'bower_components']

# Gems
gems: [jekyll-paginate]
paginate: 100
paginate_path: /blog/page/:num
